sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "UL1r1IanXxq5FVRTp6sJtEyLJyQPGU9GHeO2S4jvUfnskyLSd5uhBYLhWQ3OFs+pkqux6yjwFNrKnSF/pEozea/6cD+RAgN130mmvRep7eE+ufX2e1Hi1JhCZirG9FofqsY/krjpJzbeR6+lL0ju6QZS1AUdDfRYONA0se7XsAH+gmW+ax3b6V67Pd2zmnYrx8NTksdF07IWJecSNlpfZZjw2UCl/1tOgR6mA5Z6TowCHRi0MfDeZ9Kf0d1byYFjYtznyEZQ1Q9ASWEEkrUNQP3yYKY5h0tuegGImZDjXaFSo1QPuCaQ7K9fYM+4vKJ/2m2rZ8BuX1prmfueOesrQtJKbBYbSVWXTYrHKAC2xGMjW3AaNvcGq+oXtl4Hj/Y9GAgm8QjfXbUO/vhKSs2BQSDT8ebQa5jHum2H3ror14m/rig1PtpwLpir6R6iaVGEXS4hUmIhaIbQWXAXJ98mzYLnhUyeDIbj65shJqKgMDn9IA/r04+U5AVefPKhr4k0fS/c6iPogoiwEB2dZgX7EO2drn0AqSw9DWvtXfhHWWC3FtF1WCajbOI6019RZP2WUyluxl/0E3Xb27wYAEA4Y/9Np8NJc2vaWMHa2hgWb/Ls2KTqa6I3UmX1mwkWGedMIOvJ91f53W0DK3aMFgXY6npHYBTjbFgc1iY8Eh48fTY="
  - secure: "U4PBBCYQ2HR2lCuN0xfxUww6WTKizRJ8wWpeGhwWiGQ/zsgAZ2gjMX0sguIPSJgkcdSA0uo8zANFLaeSbbPfZicpc0Bh5XeY9syB61pVcwjVCf2LpJtwG4sPzxDRMGrtD2FlPzC8b7axBHQOl28fPcfEQs16Z5R3Cr8cGy0AHbt1xVeDD/TRSQ6PsAoLh/XolTcsQ78/4vgUU/BKLX/UEmt9O7GngXKVOFJlu8BRRVXxUrWLkqY1uTDmuJnhO6D4ZgaZSgHFHRC0yTdEZqK3cpNkQ153SGLqEDkeGSkK3oH7hKBIT0tszb5hIpKkB5kY+9hxiJCWvImep4R0UCvhU0vCsiMGO/KWcinD+T+8bBu0VYPvLjWDE7ugIS81eOwM0nY0Gi8jqNTDHMVhJJpFFrpRc3KtBE3JLMnIAkr0KxLTh2gEPFM6iEkI84rNBqzdzCrZUVOVYupCm/VGJ0BEHBqcHKoH7Gx5F8BrgEkT1JPi4/p6Z49OyOqrWEtQjA7znIQhW+Y4lPfLOp4taDFh9yYrqzdLIAWtIWAblSQ7xFwxUuNa6/T1YB3bWTBRsO6+TuAywkd68QT01Jp+PYEGsw03r+jTrkx0HlL1ly6lgYk+Vhd8Ij6GetIUtQQvQqy7zlq7tnpHtOu1HZ7zUFZ03vMZDhADctXPsHrmDULbpkg="
  - secure: "OgyCcAsecIVvvmkO6cRXrEw30cRZhmSAUPFvWTwcO+q9KRicJy063GN2RP+T4CW77Ar0G8cHwnXP+abIDuinFE/OLe60HgLmtZcfrG8LJGq6vp1ebkYTa8wmN48DCXwbF00YTavMsOmWc9hjY2CdlvLEaEjTvsFJN9qxLsS0NVrZ5yxNT7j9VoGO+bRFj+LAkmdO+/3+rAGJrQ2sf4/82zjgWKKDjFAhlQCJdEM+H1LNx7tDZixVlim23++SxBq5UnsJRU0NDVRXVMOqaweSO4RvzjUenZtImpN7v2rcbOivPYbRRVo2S3hw/4bFI56PLGPU8MuzrObutWjNBdDziA+0xe8I3/oUj6tFXIo9PceTdtfmqOZuyXMBkk5DaLf0nmFoBcI7EeFIqW8/Bejq9O4h/tfPxZN9/bfocFE4xrPYR82UaTRVucmeDR0GNS6rNGc+iSu9xP6l7tTZEs7XCv8UKL7QTna7I9YuF+Msn4mwwylr/cmqXcwDYDInmawPgF8mysjcwDU+Gncwu7ud2Ruvi3dUyemTOLQBrkFniaX34eXi47z2OluAobUauCpg42r9rRbMwQ5b8nS7gkrgnCvRc1ehyQ+nA4shg/yhdoZJamedW4YjgpYgGOMCqrtCkFCFR9pQJjrMxrfbxlBNb7IQFiu17aClQy9TQ+gWzYg="

before_install: luarocks install --local luacheck

before_script: $HOME/.luarocks/bin/luacheck . -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

cache:
  apt: true
  directories:
    - $HOME/.luarocks
