name: Package Retail

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*classic*'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'skip ci') != true

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install luarocks pandoc
          luarocks install --local luacheck
          wget -O ~/release.sh https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
          chmod +x ~/release.sh

      - name: Run luacheck
        run: ~/.luarocks/bin/luacheck . -o 011

      - name: Package and Publish
        run: ~/release.sh
